vendor: jFrog
name: Artifactory
version: 7.61.0
website_url: https://jfrog.com/artifactory
documentation_url: https://jfrog.com/help/r/jfrog-artifactory-documentation
product_logo_url: https://media.jfrog.com/wp-content/uploads/2022/05/24134044/artifactory-Icon.png
type: cloud and self hosted
description: Artifactory provides universal management of binaries, packages, & dependencies including OCI artifacts.